### ISSUE TITLE
How to use TEST as stb-style?

### ISSUE THREAD

**Issue by ayoubelmhamdi** [Warwolt/rktest#32]
When we use the stb-style, is there any better way to integrate the `TEST`'s in main.c without changing/commenting the entry point `main()`
```c
#define DEFINE_RKTEST_IMPLEMENTATION
#include <rktest/rktest.h>

int factorial(int n) {
	int result = 1;
	for (int i = 1; i <= n; i++) {
		result *= i;
	}

	return result;
}

//int main(int argc, const char* argv[]) {
//    printf("Hello, World!\n");
//    return 0;
//}

int main(int argc, const char* argv[]) {
    return rktest_main(argc, argv);
}

TEST(simple_tests, factorial_of_negative_is_one) {
	EXPECT_EQ(factorial(-1), 1);
	EXPECT_EQ(factorial(-42), 1);
}
```

**Comment by Warwolt** [comment]
Presumably your project would consist of two binaries: the application binary itself, and then your test binary. The application binary would link against all your source files and a `main.c` function, and the test binary would link against all the source files _minus_ the `main.c`, since the test runner should have its own main function.

An example source tree could be:
```
├── src
│   ├── main.c
│   ├── factorial.c
│   └── factorial.h
├── tests
│   ├── test_main.c
|   └── factorial_tests.c
└── external
    └── rktest
        └── rktest.h
```

You would have your factorial function in a source file separate from `main.c`:

```C
// factorial.h
int factorial(int n);
```


```C
// factorial.c
int factorial(int n) {
	int result = 1;
	for (int i = 1; i <= n; i++) {
		result *= i;
	}

	return result;
}
```

```C
// main.c
#include "factorial.h"

int main(void) {
    printf("5! = %d\n", factorial(5));
}

```

You would define the rktest implementation in `test_main.c`:

```C
// test_main.c
#define DEFINE_RKTEST_IMPLEMENTATION
#include <rktest/rktest.h>

int main(int argc, const char* argv[]) {
    return rktest_main(argc, argv);
}
```

And then write the test in the `factorial_tests.c` file:

```C
// factorial_tests.c

#include <rktest/rktest.h>

#include "factorial.h"

TEST(simple_tests, factorial_of_negative_is_one) {
	EXPECT_EQ(factorial(-1), 1);
	EXPECT_EQ(factorial(-42), 1);
}
```

**Comment by Warwolt** [comment]
There's an example repo that you can use to reference how projects are usually structured when supporting unit tests, in my experience: https://github.com/Warwolt/rktest_example

**Comment by ayoubelmhamdi** [comment]
@Warwolt is this a bad behavior, and also does not work for me.
```c
#ifdef RKTEST_MAIN

int main(int argc, const char* argv[]) {
    return rktest_main(argc, argv);
}

#else

int main(int argc, const char* argv[]) {
    printf("Hello, World!\n");
    return 0;
}

#endif
```

**Comment by Warwolt** [comment]
Closing this as I feel I've explained the recommended way to integrate STB style

**Comment by ayoubelmhamdi** [comment]
> @Warwolt is this a bad behavior, and also does not work for me.
> 
> ```c
> #ifdef RKTEST_MAIN
> 
> int main(int argc, const char* argv[]) {
>     return rktest_main(argc, argv);
> }
> 
> #else
> 
> int main(int argc, const char* argv[]) {
>     printf("Hello, World!\n");
>     return 0;
> }
> 
> #endif
> ```
However, using this preprocessing `#ifdef RKTEST_MAIN` doesn't work as I expected; it can't compile like that. I tried to pass some flags to `gcc`/`clang` but it's not working. The `rktest.h` has an entry point main function that conflicts with the preprocessing.

**Comment by Warwolt** [comment]
> > @Warwolt is this a bad behavior, and also does not work for me.
> > ```c
> > #ifdef RKTEST_MAIN
> > 
> > int main(int argc, const char* argv[]) {
> >     return rktest_main(argc, argv);
> > }
> > 
> > #else
> > 
> > int main(int argc, const char* argv[]) {
> >     printf("Hello, World!\n");
> >     return 0;
> > }
> > 
> > #endif
> > ```
> 
> However, using this preprocessing `#ifdef RKTEST_MAIN` doesn't work as I expected; it can't compile like that. I tried to pass some flags to `gcc`/`clang` but it's not working. The `rktest.h` has an entry point main function that conflicts with the preprocessing.

Hi, you should not try to mix your application main with the test runner main
